<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/user/v1/user.proto

namespace User\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.v1.CreateUserInfo</code>
 */
class CreateUserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    protected $mobile = '';
    /**
     * Generated from protobuf field <code>string nickname = 2;</code>
     */
    protected $nickname = '';
    /**
     * Generated from protobuf field <code>string password = 3;</code>
     */
    protected $password = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mobile
     *     @type string $nickname
     *     @type string $password
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\User\V1\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

}

